builds:
  - main: ./main
    env:
      - GO111MODULE=on

archives:
  - format: tar.gz
    files:
      - ./main

release:
  github:
    owner: ${{ github.repository_owner }}
    name: ${{ github.repository }}
