# .goreleaser.yml
project_name: super-calculator

before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go  
    env:
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: Xedicus
    name: super-calculator
